### ISSUE TITLE
Please use class time to continue advancing web skills

### ISSUE THREAD

**Issue by jelkner** [jwploetz/itd110#1]
No commits for 11 days.  What's up?

**Comment by koibots8230** [comment]
I was working on the robotics team website with Antonio. You can see our progress here:[https://github.com/koibots8230/website]( https://github.com/koibots8230/website)

I also started working on CIW

**Comment by jwploetz** [comment]
I was working on the robotics team website with Antonio. You can see our progress here:[https://github.com/koibots8230/website]( https://github.com/koibots8230/website)

I also started working on CIW
